# -*- coding: utf-8 -*-
"""Resume_Job_Matching.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14dWq26V3XwXSdAB8mtEhHnDLgA7PRV5J

# NLP-Based Resume and Job Description Matching Using TF-IDF and Cosine Similarity

##  Problem Statement

Recruiters may need to screen many resumes for a job opening. The project develops an NLP-based system that automatically compares resume text with job-description text and ranks candidates according to textual relevance.

The system is intended as an initial screening aid, not as a final hiring decision.

### Problem Relevance

* Helps recruiters and hiring teams identify relevant resumes quickly.
* Processes unstructured resume and job description text using NLP techniques.
* Compares resumes with job descriptions based on text similarity.
* Ranks candidates from the most relevant to the least relevant.
* Reduces manual effort and saves time during the initial screening process.
* Can help improve the efficiency of the recruitment process.

## Dataset

**Dataset:** `med2425/resume-job-fit-merged-v1`

**Source:** Hugging Face Datasets  
https://huggingface.co/datasets/med2425/resume-job-fit-merged-v1
"""

# Install required libraries
!pip -q install datasets nltk scikit-learn pandas matplotlib seaborn

# Import libraries
import re
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

from datasets import load_dataset
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Download NLTK resources
nltk.download("stopwords")
nltk.download("wordnet")
nltk.download("omw-1.4")

"""## Load Dataset

The dataset is downloaded directly from Hugging Face using the `datasets` library.

"""

# Load the dataset
dataset = load_dataset("med2425/resume-job-fit-merged-v1")

print(dataset)

# Convert the training split to a pandas DataFrame
full_train_df = dataset["train"].to_pandas()

print("Original training records:", len(full_train_df))
print("Columns:", full_train_df.columns.tolist())

"""##  Select the 1,000-Record Working Dataset

The original training data is retained in `full_train_df`. A reproducible sample of 1,000 records is used for the project implementation.

"""

# Select 1,000 records for the project
df = full_train_df.sample(
    n=min(1000, len(full_train_df)),
    random_state=42
).reset_index(drop=True)

print("Working dataset shape:", df.shape)

# Inspect the dataset
display(df.head())

print("\nMissing values:")
print(df.isnull().sum())

print("\nLabel distribution:")
print(df["label"].value_counts())

# Plot label distribution
plt.figure(figsize=(8, 5))
df["label"].value_counts().plot(kind="bar")
plt.title("Resume-Job Fit Label Distribution")
plt.xlabel("Fit Label")
plt.ylabel("Number of Records")
plt.xticks(rotation=0)
plt.show()

"""##  Inspect a Sample Resume and Job Description

"""

# Display one example
print("RESUME")
print("=" * 80)
print(df.loc[0, "resume"])

print("\nJOB DESCRIPTION")
print("=" * 80)
print(df.loc[0, "jd"])

print("\nLABEL")
print("=" * 80)
print(df.loc[0, "label"])

"""## Text Preprocessing



"""

# Create preprocessing resources
stop_words = set(stopwords.words("english"))
lemmatizer = WordNetLemmatizer()

def preprocess_text(text):
    text = str(text).lower()

    # Remove URLs
    text = re.sub(r"http\S+|www\S+|https\S+", " ", text)

    # Remove email addresses
    text = re.sub(r"\S+@\S+", " ", text)

    # Remove numbers
    text = re.sub(r"\d+", " ", text)

    # Keep alphabetic characters and spaces
    text = re.sub(r"[^a-zA-Z\s]", " ", text)

    # Tokenization
    tokens = text.split()

    # Stopword removal
    tokens = [word for word in tokens if word not in stop_words]

    # Lemmatization
    tokens = [lemmatizer.lemmatize(word) for word in tokens]

    return " ".join(tokens)

# Test preprocessing on one resume and one job description
print("Original resume:")
print(df.loc[0, "resume"][:800])

print("\nPreprocessed resume:")
print(preprocess_text(df.loc[0, "resume"])[:800])

print("\nPreprocessed job description:")
print(preprocess_text(df.loc[0, "jd"])[:800])

# Preprocess the 1,000 records
print("Preprocessing resumes...")
df["clean_resume"] = df["resume"].apply(preprocess_text)

print("Preprocessing job descriptions...")
df["clean_jd"] = df["jd"].apply(preprocess_text)

print("Preprocessing completed!")

"""##  Methodology and Algorithm Selection

### TF-IDF
TF-IDF converts text documents into numerical vectors. Terms that are informative within a document receive greater importance than terms that occur across many documents.

### Cosine Similarity
Cosine similarity measures the angle between two TF-IDF vectors. A higher value indicates greater textual similarity.

### Why these methods?
TF-IDF and cosine similarity are simple, interpretable document-similarity methods and are appropriate for a small information-retrieval project. They also align closely with the NLP techniques covered in the laboratory work.

### Methodology Flow

```text
Resume + Job Description
          ↓
   Text Preprocessing
          ↓
Tokenization + Stopword Removal
          ↓
      Lemmatization
          ↓
        TF-IDF
          ↓
  Cosine Similarity
          ↓
    Matching Score
          ↓
    Resume Ranking
          ↓
 Precision@K / Recall@K
```

##  TF-IDF Representation
"""

# Build a shared TF-IDF vocabulary for resumes and job descriptions
all_text = pd.concat(
    [df["clean_resume"], df["clean_jd"]],
    ignore_index=True
)

tfidf_vectorizer = TfidfVectorizer(
    max_features=10000,
    ngram_range=(1, 2)
)

tfidf_matrix = tfidf_vectorizer.fit_transform(all_text)

n = len(df)

resume_vectors = tfidf_matrix[:n]
jd_vectors = tfidf_matrix[n:]

print("TF-IDF matrix shape:", tfidf_matrix.shape)
print("Resume vectors:", resume_vectors.shape)
print("Job-description vectors:", jd_vectors.shape)

"""##  Baseline Resume–Job Similarity

First, calculate similarity for each original resume–job pair. This gives a baseline similarity score for the labelled records.

"""

# Efficiently calculate similarity for corresponding resume-JD pairs.
# Because TF-IDF vectors are L2-normalized, their row-wise dot product
# is equivalent to cosine similarity.

pair_similarity = np.asarray(
    resume_vectors.multiply(jd_vectors).sum(axis=1)
).ravel()

df["similarity_score"] = pair_similarity
df["match_percentage"] = df["similarity_score"] * 100

display(
    df[
        ["label", "similarity_score", "match_percentage"]
    ].head(10)
)

"""##  Proper Resume Ranking for One Job Description


"""

# Select one job description as the query
query_job = df.loc[0, "jd"]
clean_query_job = preprocess_text(query_job)

print("Selected Job Description:")
print(query_job)

# Fit TF-IDF on all resumes plus the query job description
retrieval_documents = (
    df["clean_resume"].tolist() + [clean_query_job]
)

retrieval_vectorizer = TfidfVectorizer(
    max_features=10000,
    ngram_range=(1, 2)
)

retrieval_matrix = retrieval_vectorizer.fit_transform(
    retrieval_documents
)

resume_vectors_query = retrieval_matrix[:-1]
job_vector_query = retrieval_matrix[-1]

print("Resume matrix:", resume_vectors_query.shape)
print("Query job vector:", job_vector_query.shape)

# Calculate similarity between the query job and every resume
query_scores = cosine_similarity(
    job_vector_query,
    resume_vectors_query
).ravel()

retrieval_df = df.copy()
retrieval_df["similarity_score"] = query_scores
retrieval_df["match_percentage"] = query_scores * 100

retrieval_df = retrieval_df.sort_values(
    by="similarity_score",
    ascending=False
).reset_index(drop=True)

retrieval_df["rank"] = np.arange(1, len(retrieval_df) + 1)

"""## 13. Top Matching Resumes

"""

# Display the Top 10 resumes
top_10 = retrieval_df.head(10)

display(
    top_10[
        ["rank", "label", "similarity_score", "match_percentage"]
    ]
)

# Show details of the Top 10 matches
for _, row in top_10.iterrows():
    print("=" * 80)
    print("Rank:", row["rank"])
    print("Label:", row["label"])
    print("Match Percentage:", round(row["match_percentage"], 2), "%")
    print("\nResume:")
    print(row["resume"][:1000])
    print()

"""##  Evaluation: Precision@K and Recall@K

For a valid information-retrieval evaluation, relevance labels must belong to the **same job-description query** being evaluated.

Therefore, instead of using the label from an unrelated job description, the evaluation below groups records by their exact job description. It evaluates only job descriptions that have enough candidate records to form a ranked list.

`Good Fit` and `Potential Fit` are treated as relevant; `No Fit` is treated as not relevant.

If the 1,000-record sample does not contain enough repeated job descriptions, the notebook will report that Precision@K/Recall@K cannot be reliably estimated from this sample rather than fabricating a metric.

"""

# Define relevance
RELEVANT_LABELS = {"Good Fit", "Potential Fit"}

eval_df = df.copy()
eval_df["relevant"] = eval_df["label"].isin(RELEVANT_LABELS)

# Calculate pairwise similarity again for evaluation
eval_df["similarity_score"] = pair_similarity

def precision_at_k(group, k):
    top_k = group.sort_values(
        "similarity_score",
        ascending=False
    ).head(k)

    return top_k["relevant"].mean()

def recall_at_k(group, k):
    total_relevant = group["relevant"].sum()

    if total_relevant == 0:
        return np.nan

    top_k = group.sort_values(
        "similarity_score",
        ascending=False
    ).head(k)

    return top_k["relevant"].sum() / total_relevant

# Evaluate only groups with at least K candidates
k_values = [5, 10]

evaluation_rows = []

for k in k_values:
    eligible_groups = [
        group for _, group in eval_df.groupby("jd")
        if len(group) >= k and group["relevant"].sum() > 0
    ]

    if len(eligible_groups) == 0:
        evaluation_rows.append({
            "K": k,
            "Precision@K": np.nan,
            "Recall@K": np.nan,
            "Eligible job descriptions": 0
        })
        continue

    precisions = [
        precision_at_k(group, k)
        for group in eligible_groups
    ]

    recalls = [
        recall_at_k(group, k)
        for group in eligible_groups
    ]

    evaluation_rows.append({
        "K": k,
        "Precision@K": np.mean(precisions),
        "Recall@K": np.mean(recalls),
        "Eligible job descriptions": len(eligible_groups)
    })

evaluation_results = pd.DataFrame(evaluation_rows)

display(evaluation_results)

if evaluation_results["Eligible job descriptions"].max() == 0:
    print(
        "No job description in the 1,000-record sample has enough "
        "candidate records for reliable Precision@K/Recall@K evaluation."
    )
    print(
        "Do not report fabricated Precision@K/Recall@K values. "
        "Use a larger sample or a separately labelled retrieval set."
    )

"""##  Results and Graphs

"""

# Top-10 similarity graph for the selected job description
plot_df = retrieval_df.head(10)

plt.figure(figsize=(10, 6))
plt.bar(
    plot_df["rank"].astype(str),
    plot_df["match_percentage"]
)

plt.xlabel("Resume Rank")
plt.ylabel("Match Percentage")
plt.title("Top 10 Resume-Job Matching Scores")
plt.show()

# Average baseline similarity by actual fit label
label_similarity = (
    df.groupby("label")["similarity_score"]
      .mean()
      .sort_values(ascending=False)
)

display(label_similarity.to_frame("Average Similarity"))

plt.figure(figsize=(8, 5))
label_similarity.plot(kind="bar")

plt.xlabel("Fit Label")
plt.ylabel("Average Cosine Similarity")
plt.title("Average Similarity by Resume-Job Fit Label")
plt.xticks(rotation=0)
plt.show()

"""##  Final Matching Application

"""

# Final interactive matching function

def match_resumes(job_description, top_k=10):
    clean_job = preprocess_text(job_description)

    documents = df["clean_resume"].tolist() + [clean_job]

    vectorizer = TfidfVectorizer(
        max_features=10000,
        ngram_range=(1, 2)
    )

    matrix = vectorizer.fit_transform(documents)

    resume_matrix = matrix[:-1]
    job_vector = matrix[-1]

    scores = cosine_similarity(
        job_vector,
        resume_matrix
    ).ravel()

    results = df.copy()
    results["similarity_score"] = scores
    results["match_percentage"] = scores * 100

    results = results.sort_values(
        "similarity_score",
        ascending=False
    ).reset_index(drop=True)

    results["rank"] = np.arange(1, len(results) + 1)

    return results.head(top_k)

# Test the Resume-Job Matching System

user_job_description = """
Job Title: Data Analyst Intern

We are looking for a candidate with skills in Python, SQL, Pandas, NumPy,
data analysis, machine learning, and data visualization. Knowledge of
Scikit-learn and experience working with datasets is preferred.
Strong analytical and problem-solving skills are required.
"""

# Get top 10 resumes based on similarity
user_results = match_resumes(
    user_job_description,
    top_k=10
)

# Display results as a table
display(
    user_results[
        ["rank", "similarity_score", "match_percentage", "resume"]
    ].reset_index(drop=True)
)

"""###Limitations

1. TF-IDF focuses mainly on word overlap and may not capture deeper meaning.
2. Different words with similar meanings may receive low similarity.
3. Noisy or inconsistent resume text can affect preprocessing.
4. The results depend on the quality of the dataset and labels.
5. Using 1,000 records limits the size of the resume collection.
6. Dataset bias may affect the results.
7. Similarity scores should support screening, not replace human hiring decisions.

Conclusion

This project develops an NLP-based resume and job-description matching system using text preprocessing, TF-IDF, and cosine similarity. It ranks resumes based on their similarity to a job description and provides Top-K matching results.

The project demonstrates how NLP can be applied to automate and simplify resume screening.
"""